foreground                      #96a5b3
background                      #2d2a27
selection_foreground            #b5bcc8
selection_background            #1e3a72

cursor                          #a8a8a8
cursor_text_color               #2d2a27

color0  #2d2a27
color8  #484848

color1  #b5524d
color9  #c45151

color2  #578549
color10 #63995a

color3  #a39e24
color11 #c9a86d

color4  #436292
color12 #5c85a6

color5  #886898
color13 #aa7fcf

color6  #1c878b
color14 #4ba1ac

color7  #96a5b3
color15 #b5bcc8
